version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: chat_backend
    ports:
      - "5000:5000"
    environment:
      OLLAMA_MODEL: "llama3" # Or your preferred model
    networks:
      - app-network
    depends_on:
      - ollama

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: chat_frontend
    ports:
      - "8501:8501"
    networks:
      - app-network
    depends_on:
      - backend

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ollama_data: